### ISSUE TITLE
I think there is some mistake in the implementation of logic 

### ISSUE THREAD

**Issue by Harshal0506** [Tarang-singhal/split-wise-algorithm#1]
![image](https://user-images.githubusercontent.com/66555099/109153027-516d9a00-7792-11eb-88c9-3bc12f68e770.png)

According to me, the solution must be

![image](https://user-images.githubusercontent.com/66555099/109153374-d8bb0d80-7792-11eb-970b-b89fd22d5a73.png)

You made an amazing project buddy
Kindly update me if I am wrong 
Thank you and well wishes 😊

**Comment by Tarang-singhal** [comment]
well actually the goal of my algorithm is to reduce no. of edges
but in this case -  edges will remain 3, but the amount flow, may change
so, your answer is also correct

**Comment by Harshal0506** [comment]
S

**Comment by Harshal0506** [comment]
**sorry** about the above example it was not a proper example to convey my issue


![image](https://user-images.githubusercontent.com/66555099/109271569-b62e0080-7835-11eb-988c-bebbac9afccc.png)

Kindly have a look 
According to me minimum transaction needed is **2** but according to your logic implemented its giving **3**

**Comment by Tarang-singhal** [comment]
Ok, I will check.
